### ISSUE TITLE
processUnknownAttribute() needing to be called explicitly in SpatialParser

### ISSUE THREAD

**Issue by bhavyejain** [bhavyejain/jsbml#1]
Handling of unknown attributes is already done in SBMLReader.

https://github.com/sbmlteam/jsbml/blob/8ea32d6aef94624f0b9110e8a41a58303b2a8c99/core/src/org/sbml/jsbml/xml/stax/SBMLReader.java#L1196

But to get the `UnknownPackageAttributeValidationFunction` working for `spatial`, it had to be added explicitly in `SpatialParser`. This should not have been required.

https://github.com/bhavyejain/jsbml/blob/5c9badd21883c6c69aea256811d4c42bfbec058a/extensions/spatial/src/org/sbml/jsbml/xml/parsers/SpatialParser.java#L252-L254

The problem can be tested by running tests for the rule spatial-20401 from SpatialSpeciesPluginConstraints.

**Comment by niko-rodrigue** [comment]
Just had a look at this rule. By default, the unknown attribute will be added to the Species instance, not the SpatialSpeciesPlugin. So you could look both on the Species and the SpatialSpeciesPlugin for unknown spatial attributes for this rule. Then the second call to processUnknownAttribute won't be necessary.

Or may be even better, you let the `if` there but add a check for `contextObject instanceof SBasePlugin` and then after the call to `processUnknownAttribute` you return directly `true` so that the unknown attribute is not added twice on two different objects.

Btw, `super.` is not needed there, you can just call the method directly.

**Comment by bhavyejain** [comment]
@niko-rodrigue I get the problem now!
I have solved it using the second approach. 
I was able to do it using the first approach also, but the second one seemed better.
